//! `phx compile` handler — compile a standalone file to `.phx0` bytecode.
//!
//! This module is the entry point for [`run_compile`]. It accepts a single entry
//! file and an output path, runs the standalone compile pipeline, verifies the
//! encoded module, and writes bytes to disk. Project mode is explicitly rejected;
//! use [`super::run_build`] or run outside a project tree instead.
//!
//! ```text
//! CompileCommandArgs + <file.phx> + -o <output.phx0>
//!       │
//!       ▼
//! resolve_check_mode ──► Standalone only (Project ──► Usage)
//!       │
//!       ▼
//! check_standalone_unit_with_context
//!       │
//!       ▼
//! lint_typed_or_exit
//!       │
//!       ▼
//! compile_compilation_unit ──► verify ──► encode ──► fs::write
//!       │
//!       ▼
//! CliExit::Ok
//! ```
//!
//! ## Project vs standalone
//!
//! **Standalone only.** If `resolve_check_mode` returns
//! [`crate::workflow::CompileMode::Project`], the handler reports a usage error
//! directing the user to `phx build`. Lint policy defaults to warn-only unless
//! `--deny` is passed on the CLI.
//!
//! ## Compiler passes invoked
//!
//! Load, resolve, type check, lint, lower, and codegen via
//! [`phx_compiler::check_standalone_unit_with_context`] and
//! [`phx_compiler::compile_compilation_unit`], followed by
//! [`phx_bytecode::verify`] on the in-memory module before serialization. No
//! VM execution.
//!
//! ## Exit codes
//!
//! | Outcome | [`crate::exit::CliExit`] |
//! | --- | --- |
//! | Success | [`CliExit::Ok`] |
//! | Missing file or `-o`, project mode, workflow or load-context errors | [`CliExit::Usage`] |
//! | Source read, encode, or output write failure | [`CliExit::Io`] |
//! | Check, compile, or lint deny | [`CliExit::Compile`] |
//! | Bytecode verification failure | [`CliExit::Verify`] |
//!
//! ## Public entry points
//!
//! - [`run_compile`] — run `phx compile` for the given file, output path, and flags.

use std::fs;

use phx_bytecode::verify;
use phx_compiler::{check_standalone_unit_with_context, compile_compilation_unit};

use phx_diagnostics::LintDenyConfig;

use crate::args::{CompileCommandArgs, effective_lint_deny};
use crate::color::ColorChoice;
use crate::exit::CliExit;
use crate::lints::lint_typed_or_exit;
use crate::report::Reporter;
use crate::workflow::{CompileMode, resolve_check_mode};

/// Runs `phx compile <file> -o <output.phx0>` — standalone file to bytecode file.
///
/// Requires both an entry path and `-o` output. Rejects project-mode resolution
/// with a usage message. Runs check → lint → compile → verify, then writes the
/// encoded [`phx_bytecode::BytecodeModule`] to the output path.
///
/// # Errors
///
/// Returns a non-[`CliExit::Ok`] variant instead of panicking:
///
/// - [`CliExit::Usage`] — missing `<file.phx>` or `-o`, project-mode invocation,
///   workflow resolution failure, or standalone load-context error.
/// - [`CliExit::Io`] — cannot read source, encode the module, or write the output file.
/// - [`CliExit::Compile`] — type-check, codegen, or lint deny failure.
/// - [`CliExit::Verify`] — generated bytecode fails structural verification.
///
/// # Panics
///
/// Never panics on user input or malformed source.
pub fn run_compile(args: CompileCommandArgs, color: ColorChoice, verbose: bool) -> CliExit {
    let style = crate::color::diagnostic_style(color);
    let reporter = Reporter::new(&style);

    let file = match &args.file_args.file {
        Some(f) => f.clone(),
        None => {
            reporter.usage_error("missing required argument <file.phx>");
            return CliExit::Usage;
        }
    };
    let out = match args.output {
        Some(o) => o,
        None => {
            reporter.usage_error("missing required argument -o <output.phx0>");
            return CliExit::Usage;
        }
    };

    let mode = match resolve_check_mode(&file, &args.file_args, None) {
        Ok(CompileMode::Standalone { options }) => options,
        Ok(CompileMode::Project { .. }) => {
            reporter.usage_error(
                "phx compile does not support project mode; use `phx build` or run outside a project directory",
            );
            return CliExit::Usage;
        }
        Err(e) => {
            reporter.usage_error(&e.to_string());
            return CliExit::Usage;
        }
    };

    let source = match fs::read_to_string(&file) {
        Ok(s) => s,
        Err(e) => {
            reporter.io_error(&e.to_string());
            return CliExit::Io;
        }
    };

    let ctx = match mode.load_context() {
        Ok(c) => c,
        Err(e) => {
            reporter.project_error(&e.to_string());
            return CliExit::Usage;
        }
    };

    reporter.verbose(verbose, &format!("compiling {}...", file.display()));
    let unit = match check_standalone_unit_with_context(&mode, &ctx) {
        Ok(u) => u,
        Err(e) => {
            reporter.compile_error(&e, Some(&source), Some(&file));
            return CliExit::Compile;
        }
    };
    if let Err(exit) = lint_typed_or_exit(
        &unit.typed,
        &effective_lint_deny(
            args.file_args.lint_deny.as_ref(),
            &LintDenyConfig::warn_only(),
        ),
        &style,
        &reporter,
        Some(&source),
        Some(&file),
    ) {
        return exit;
    }
    let module = match compile_compilation_unit(&unit) {
        Ok(m) => m,
        Err(e) => {
            reporter.compile_error(&e, Some(&source), Some(&file));
            return CliExit::Compile;
        }
    };

    if let Err(e) = verify(&module) {
        reporter.verify_error(&e.to_string());
        return CliExit::Verify;
    }

    let bytes = match module.encode() {
        Ok(b) => b,
        Err(e) => {
            reporter.io_error(&e.to_string());
            return CliExit::Io;
        }
    };

    if let Err(e) = fs::write(&out, bytes) {
        reporter.io_error(&e.to_string());
        return CliExit::Io;
    }

    reporter.verbose(verbose, &format!("wrote {}", out.display()));
    CliExit::Ok
}
