[package]
name = "phx-integration-tests"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
publish = false

[lints]
workspace = true

[dev-dependencies]
phx-bytecode = { path = "../../source/phx-bytecode" }
phx-compiler = { path = "../../source/phx-compiler" }
phx-diagnostics = { path = "../../source/phx-diagnostics" }
phx-vm = { path = "../../source/phx-vm" }
